# Gas benchmark data - EDA v2

#### Maria Silva, December 2025

In [1]:
import os
import sys
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

import warnings
warnings.filterwarnings("ignore")

In [2]:
# plotting theme
sns.set_theme(
    style="whitegrid", palette="Set2", rc={"figure.dpi": 500, "axes.titlesize": 15}
)

## Load data from DB

In this analysis, we are using data generated by running the [EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks). The database is hosted on a PostgreSQL server managed by the Nethermind team.

In [3]:
# Main directories
current_path = os.getcwd()
repo_dir = os.path.abspath(os.path.join(current_path, ".."))
report_dir = os.path.join(
    repo_dir, "reports", "opcode_run_times_estimation", "2026-01-10_2026-01-12"
)
src_dir = os.path.join(repo_dir, "src")

# Other files
opcodes_file_name = os.path.abspath(
    os.path.join(repo_dir, "src", "opcodes_in_test_name.txt")
)
with open(opcodes_file_name, "r") as f:
    opcodes_in_test_name_list = [line.strip() for line in f.readlines()]

In [4]:
sys.path.append(src_dir)
import operation_types

In [5]:
# Secrets for acessing xatu clickhouse and erigon
with open(os.path.join(repo_dir, "secrets.json"), "r") as file:
    secrets_dict = json.load(file)

# Credentials for gas bench postgresql
user = secrets_dict["gas_bench_username"]
password = secrets_dict["gas_bench_password"]

In [6]:
gas_bench_db_url = f"postgresql://{user}:{password}@perfnet.core.nethermind.dev:5432/monitoring"
start_date = "2025-12-19"
query_str = f"""
SELECT 
    test_title,
    client_name,
    raw_run_duration_ms AS run_duration_ms,
    opcount,
    ingestion_timestamp
FROM repricings_new
WHERE ingestion_timestamp >= '{start_date}'::timestamp
"""
engine = create_engine(gas_bench_db_url)
raw_df = pd.read_sql(query_str, con=engine)
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43896 entries, 0 to 43895
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   test_title           43896 non-null  object
 1   client_name          43896 non-null  object
 2   run_duration_ms      43896 non-null  float64
 3   opcount              43896 non-null  int64
 4   ingestion_timestamp  43896 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(1), int64(1), object(2)
memory usage: 1.7+ MB

Now we can parse the test name info:

In [7]:
df = raw_df.copy()
df["test_file"] = (
    df["test_title"].str.replace("tests_benchmark_", "").str.split(".py").str[0]
)
df["test_name"] = df["test_title"].str.split(".py__").str[1].str.split("[").str[0]
df["test_opcode"] = np.where(
    df["test_name"].isin(opcodes_in_test_name_list),
    df["test_name"].str.split("_").str[1].str.upper(),
    df["test_title"].str.split("opcode_").str[1].str.split("-").str[0],
)
df["test_opcode"] = df["test_opcode"].str.split("]").str[0]
df["test_params_str"] = (
    df["test_title"]
    .str.split("[")
    .str[1]
    .str.split("]")
    .str[0]
    .str.split("benchmark_test-")
    .str[1]
)
df["test_params"] = (
    df["test_params_str"]
    .str.split("-")
    .apply(
        lambda x: (
            [item for item in x if item[:6] not in ["opcode", ""]]
            if isinstance(x, list)
            else []
        )
    )
)
df["test_params"] = np.where(
    df["test_params"].str.len() == 0, np.nan, df["test_params"]
)
# alt_bn precompiles
df["test_opcode"] = np.where(
    (df["test_name"] == "test_alt_bn128") & (df["test_params_str"].str.contains("add")),
    "ECADD",
    df["test_opcode"],
)
df["test_opcode"] = np.where(
    (df["test_name"] == "test_alt_bn128") & (df["test_params_str"].str.contains("mul")),
    "ECMUL",
    df["test_opcode"],
)
# BLS12 precompiles
df["test_opcode"] = np.where(
    df["test_name"] == "test_bls12_381",
    df["test_params_str"].str.split("-").str[0].str.upper(),
    df["test_opcode"],
)
df

,test_title,client_name,run_duration_ms,opcount,ingestion_timestamp,test_file,test_name,test_opcode,test_params_str,test_params
0,test_account_query.py__test_ext_account_query_...,geth,677.966430,800,2026-01-11 18:14:09.323266+00:00,test_account_query,test_ext_account_query_warm,CALLCODE,initial_storage_True-initial_balance_True-empt...,"[initial_storage_True, initial_balance_True, e..."
1,test_memory.py__test_mcopy[fork_Prague-benchma...,geth,270.079250,3000,2026-01-11 18:14:09.323266+00:00,test_memory,test_mcopy,MCOPY,fixed_src_dst_True-copy_size_32-32 bytes-opcou...,"[fixed_src_dst_True, copy_size_32, 32 bytes, o..."
2,test_stack.py__test_push[fork_Prague-benchmark...,geth,1566.435300,70000,2026-01-11 18:14:09.323266+00:00,test_stack,test_push,PUSH14,opcode_PUSH14-opcount_70000.0K,[opcount_70000.0K]
3,test_identity.py__test_identity_fixed_size[for...,geth,448.794700,800,2026-01-11 18:14:09.323266+00:00,test_identity,test_identity_fixed_size,IDENTITY,size_0-opcount_800.0K,"[size_0, opcount_800.0K]"
4,test_log.py__test_log_benchmark[fork_Prague-be...,geth,490.989140,27,2026-01-11 18:14:09.323266+00:00,test_log,test_log_benchmark,LOG0,log_size_1024-mem_size_256-opcode_LOG0-opcount...,"[log_size_1024, mem_size_256, opcount_27.0K]"
...,...,...,...,...,...,...,...,...,...,...
43891,test_block_context.py__test_blockhash[fork_Pra...,nethermind,265.882870,10000,2026-01-12 05:05:43.444247+00:00,test_block_context,test_blockhash,BLOCKHASH,genesis-opcount_10000.0K,"[genesis, opcount_10000.0K]"
43892,test_control_flow.py__test_gas_op[fork_Prague-...,nethermind,119.687325,12000,2026-01-12 05:05:43.444247+00:00,test_control_flow,test_gas_op,GAS,opcount_12000.0K,[opcount_12000.0K]
43893,test_stack.py__test_push[fork_Prague-benchmark...,nethermind,575.518430,49000,2026-01-12 05:05:43.444247+00:00,test_stack,test_push,PUSH2,opcode_PUSH2-opcount_49000.0K,[opcount_49000.0K]
43894,test_log.py__test_log_benchmark[fork_Prague-be...,nethermind,261.624400,27,2026-01-12 05:05:43.444247+00:00,test_log,test_log_benchmark,LOG2,log_size_1024-mem_size_1024-opcode_LOG2-opcoun...,"[log_size_1024, mem_size_1024, opcount_27.0K]"
43895,test_memory.py__test_mcopy[fork_Prague-benchma...,nethermind,131.364520,1500,2026-01-12 05:05:43.444247+00:00,test_memory,test_mcopy,MCOPY,fixed_src_dst_True-copy_size_1024-1MiB-opcount...,"[fixed_src_dst_True, copy_size_1024, 1MiB, opc..."

In [8]:
df[df["test_opcode"].isna()]["test_name"].unique()

array([], dtype=object)

## Opcode counts

In [9]:
df["opcount"].value_counts()

opcount
14000     1128
70000      972
21000      948
35000      936
7000       936
          ...
375         12
280         12
52500       12
128         12
140000      12
Name: count, Length: 177, dtype: int64

In [10]:
0 in df["opcount"].value_counts().index

False

In [11]:
df["opcount"].isna().sum()/len(df)

np.float64(0.0)

Ok, no empty opcode counts now.

## Run times

In [12]:
df['run_duration_ms'].describe()

count    43896.000000
mean       623.025306
std        897.685728
min          0.000000
25%        162.357192
50%        346.527650
75%        731.853865
max      15415.144000
Name: run_duration_ms, dtype: float64

In [13]:
sum(df["run_duration_ms"]==0.0)/len(df)

0.0002733734281027884

Ok, almost no test with zero run time

In [14]:
df[df["run_duration_ms"]==0.0]

,test_title,client_name,run_duration_ms,opcount,ingestion_timestamp,test_file,test_name,test_opcode,test_params_str,test_params
1048,test_sha256.py__test_sha256_fixed_size[fork_Pr...,geth,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
4718,test_sha256.py__test_sha256_fixed_size[fork_Pr...,besu,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
8380,test_sha256.py__test_sha256_fixed_size[fork_Pr...,reth,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
12036,test_sha256.py__test_sha256_fixed_size[fork_Pr...,nethermind,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
15692,test_sha256.py__test_sha256_fixed_size[fork_Pr...,geth,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
19349,test_sha256.py__test_sha256_fixed_size[fork_Pr...,besu,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
23003,test_sha256.py__test_sha256_fixed_size[fork_Pr...,reth,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
26659,test_sha256.py__test_sha256_fixed_size[fork_Pr...,nethermind,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
30315,test_sha256.py__test_sha256_fixed_size[fork_Pr...,geth,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
33971,test_sha256.py__test_sha256_fixed_size[fork_Pr...,besu,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
37628,test_sha256.py__test_sha256_fixed_size[fork_Pr...,reth,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"
41284,test_sha256.py__test_sha256_fixed_size[fork_Pr...,nethermind,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024-opcount_500.0K,"[size_1024, opcount_500.0K]"

These are all from the same test:

In [15]:
df[df["run_duration_ms"]==0.0]["test_title"].unique()

array(['test_sha256.py__test_sha256_fixed_size[fork_Prague-benchmark_test-size_1024-opcount_500.0K]'],
      dtype=object)

## Missing opcodes

In [16]:
non_zero_df = df[df["run_duration_ms"]!=0.0].copy()
benchmarked_operations = set(non_zero_df["test_opcode"].unique().tolist())
all_operations = set(operation_types.ALL_OPERATIONS)

In [17]:
misnamed_operations = benchmarked_operations - all_operations
print(f"Number of misnamed operations: {len(misnamed_operations)}")
misnamed_operations

Number of misnamed operations: 7

{'BLS12_FP_TO_G1',
 'BLS12_FP_TO_G2',
 'JUMPDESTS',
 'KECCAK',
 'POINT',
 'RIPEMD160',
 'SHA256'}

In [18]:
missing_operations = all_operations - benchmarked_operations
print(f"Number of missing operations: {len(missing_operations)-len(misnamed_operations)}")
missing_operations

Number of missing operations: 19

{'ADDMOD',
 'BLOBHASH',
 'BLS12_G1MSM',
 'BLS12_G2MSM',
 'BLS12_MAP_FP2_TO_G2',
 'BLS12_MAP_FP_TO_G1',
 'BLS12_PAIRING_CHECK',
 'DIFFICULTY',
 'ECPAIRING',
 'INVALID',
 'JUMP',
 'JUMPDEST',
 'KECCAK256',
 'MODEXP',
 'MULMOD',
 'P256VERIFY',
 'POINT_EVALUATION',
 'POP',
 'RETURN',
 'REVERT',
 'RIPEMD-160',
 'SELFDESTRUCT',
 'SHA2-256',
 'SLOAD',
 'SSTORE',
 'STOP'}

## Test configurations

In [19]:
test_configs = non_zero_df[non_zero_df["test_params"].notna()].drop_duplicates("test_params_str")[
    ["test_opcode", "test_params"]
].sort_values("test_opcode")

test_configs

     test_opcode         test_params
716          ADD  [opcount_35000.0K]
3649         ADD  [opcount_10500.0K]
3508         ADD   [opcount_3500.0K]
1238         ADD  [opcount_24500.0K]
170          ADD  [opcount_14000.0K]
...          ...                 ...
1755         XOR  [opcount_31500.0K]
3231         XOR  [opcount_21000.0K]
2078         XOR  [opcount_14000.0K]
3060         XOR  [opcount_10500.0K]
277          XOR  [opcount_17500.0K]

[3595 rows x 2 columns]

In [20]:
relevant_test_configs=test_configs[test_configs["test_params"].apply(lambda x: len(x))>1]

relevant_test_configs["test_opcode"].unique()

array(['BALANCE', 'BLAKE2F', 'BLOCKHASH', 'BLS12_FP_TO_G1',
       'BLS12_FP_TO_G2', 'BLS12_G1ADD', 'BLS12_G2ADD', 'CALL', 'CALLCODE',
       'CALLDATACOPY', 'CALLDATALOAD', 'CALLDATASIZE', 'CALLVALUE',
       'CODECOPY', 'CREATE', 'CREATE2', 'DELEGATECALL', 'DIV', 'ECADD',
       'ECMUL', 'ECRECOVER', 'EXTCODECOPY', 'EXTCODEHASH', 'EXTCODESIZE',
       'IDENTITY', 'KECCAK', 'LOG0', 'LOG1', 'LOG2', 'LOG3', 'LOG4',
       'MCOPY', 'MLOAD', 'MSIZE', 'MSTORE', 'MSTORE8', 'POINT',
       'RETURNDATACOPY', 'RETURNDATASIZE', 'RIPEMD160', 'SDIV',
       'SELFBALANCE', 'SHA256', 'STATICCALL', 'TLOAD', 'TSTORE'],
      dtype=object)

In [21]:
relevant_test_configs

     test_opcode                                        test_params
978      BALANCE  [initial_storage_True, initial_balance_True, e...
2759     BALANCE  [initial_storage_True, initial_balance_True, e...
426      BALANCE  [initial_storage_True, initial_balance_True, e...
1225     BALANCE  [initial_storage_True, initial_balance_True, e...
3294     BALANCE  [initial_storage_True, initial_balance_True, e...
...          ...                                                ...
2753      TSTORE  [fixed_value_False, fixed_key_False, opcount_1...
3234      TSTORE  [fixed_value_False, fixed_key_False, opcount_4...
2622      TSTORE  [fixed_value_False, fixed_key_False, opcount_8...
2681      TSTORE  [fixed_value_False, fixed_key_False, opcount_1...
3120      TSTORE  [fixed_value_False, fixed_key_False, opcount_2...

[2591 rows x 2 columns]

## Estimation issues with simple opcodes

In [22]:
results_df = pd.read_csv(os.path.join(report_dir, "simple_opcodes_results.csv"))
results_df

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
0,ADD,geth,28.803542,9.183886e-02,0.024077,2.407107e-21,0.022458,0.025695,0.974046,0.973008,simple_opcode
1,ADD,reth,28.744386,5.152101e-02,0.026196,6.655718e-24,0.024811,0.027581,0.983793,0.983145,simple_opcode
2,ADD,nethermind,28.042257,2.339509e-09,0.018400,2.115981e-36,0.018094,0.018705,0.998378,0.998313,simple_opcode
3,ADD,besu,23.202074,5.716854e-01,0.196366,3.240647e-34,0.192377,0.200355,0.997574,0.997477,simple_opcode
4,ADDRESS,geth,47.426601,3.061375e-01,0.029520,2.499318e-26,0.028018,0.031022,0.983018,0.982411,simple_opcode
...,...,...,...,...,...,...,...,...,...,...,...
439,TIMESTAMP,besu,21.304192,1.357379e-01,0.028781,2.240945e-40,0.028324,0.029239,0.998314,0.998254,simple_opcode
440,XOR,geth,28.597813,4.222760e-02,0.023809,8.640066e-26,0.022542,0.025076,0.981446,0.980783,simple_opcode
441,XOR,reth,34.381666,1.464465e-10,0.008622,9.967185e-30,0.008292,0.008953,0.990288,0.989941,simple_opcode
442,XOR,nethermind,32.291447,1.186489e-05,0.029107,8.855490e-38,0.028534,0.029681,0.997416,0.997324,simple_opcode
443,XOR,besu,28.245813,1.459965e-03,0.074085,8.681120e-46,0.073330,0.074840,0.999308,0.999283,simple_opcode

In [23]:
simple_compute_opcodes = set(operation_types.SIMPLE_COMPUTE)
estimated_operations = simple_compute_opcodes - missing_operations

estimated_operations_without_errors = set(results_df["opcode"].unique().tolist())
estimated_operations_with_errors = (
    estimated_operations - estimated_operations_without_errors
)

print(
    f"Number of simple operations with estimation errors: {len(estimated_operations_with_errors)}"
)
estimated_operations_with_errors

Number of simple operations with estimation errors: 0

set()

#### Negative slopes

In [24]:
results_df[results_df["slope"]<0]

Empty DataFrame
Columns: [opcode, client, intercept, intercept_pvalue, slope, slope_pvalue, slope_conf_int_low, slope_conf_int_high, rsquared, rsquared_adj, type]
Index: []

#### Non-significant slopes (by p-value)

In [25]:
results_df[results_df["slope_pvalue"]>0.05]

Empty DataFrame
Columns: [opcode, client, intercept, intercept_pvalue, slope, slope_pvalue, slope_conf_int_low, slope_conf_int_high, rsquared, rsquared_adj, type]
Index: []

In [26]:
non_significant_ops = results_df[results_df["slope_pvalue"]>0.05]["opcode"].unique().tolist()
non_significant_ops

[]

#### Small r-squared values (besides non-significant slopes)

In [27]:
results_df[(results_df["rsquared"]<0.5) & (~results_df["opcode"].isin(non_significant_ops))]

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
23,BLOCKHASH,besu,27.777196,0.493704,0.072788,2.346026e-21,0.059894,0.085681,0.456792,0.453122,simple_opcode
28,CALLDATALOAD,geth,35.369647,0.677430,0.029068,6.299082e-19,0.023654,0.034482,0.489282,0.484954,simple_opcode

In [28]:
results_df[(results_df["rsquared"]<0.5) & (~results_df["opcode"].isin(non_significant_ops))]["opcode"].unique()

array(['BLOCKHASH', 'CALLDATALOAD'], dtype=object)