# Gas benchmark data - EDA v2

#### Maria Silva, December 2025

In [1]:
import os
import sys
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

import warnings
warnings.filterwarnings("ignore")

In [2]:
# plotting theme
sns.set_theme(
    style="whitegrid", palette="Set2", rc={"figure.dpi": 500, "axes.titlesize": 15}
)

## Load data from DB

In this analysis, we are using data generated by running the [EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks). The database is hosted on a PostgreSQL server managed by the Nethermind team.

In [3]:
# Main directories
current_path = os.getcwd()
repo_dir = os.path.abspath(os.path.join(current_path, ".."))
report_dir = os.path.join(
    repo_dir, "reports", "opcode_run_times_estimation", "2026-01-10_2026-01-12"
)
src_dir = os.path.join(repo_dir, "src")

# Other files
opcodes_file_name = os.path.abspath(
    os.path.join(repo_dir, "src", "opcodes_in_test_name.txt")
)
with open(opcodes_file_name, "r") as f:
    opcodes_in_test_name_list = [line.strip() for line in f.readlines()]

In [4]:
sys.path.append(src_dir)
import operation_types

In [5]:
# Secrets for acessing xatu clickhouse and erigon
with open(os.path.join(repo_dir, "secrets.json"), "r") as file:
    secrets_dict = json.load(file)

# Credentials for gas bench postgresql
user = secrets_dict["gas_bench_username"]
password = secrets_dict["gas_bench_password"]

In [6]:
gas_bench_db_url = f"postgresql://{user}:{password}@perfnet.core.nethermind.dev:5432/monitoring"
start_date = "2025-12-19"
query_str = f"""
SELECT 
    test_title,
    client_name,
    raw_run_duration_ms AS run_duration_ms,
    opcount,
    ingestion_timestamp
FROM repricings_new
WHERE ingestion_timestamp >= '{start_date}'::timestamp
"""
engine = create_engine(gas_bench_db_url)
raw_df = pd.read_sql(query_str, con=engine)
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58528 entries, 0 to 58527
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   test_title           58528 non-null  object
 1   client_name          58528 non-null  object
 2   run_duration_ms      58528 non-null  float64
 3   opcount              58528 non-null  int64
 4   ingestion_timestamp  58528 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(1), int64(1), object(2)
memory usage: 2.2+ MB

Now we can parse the test name info:

In [7]:
df = raw_df.copy()
df["test_file"] = (
    df["test_title"].str.replace("tests_benchmark_", "").str.split(".py").str[0]
)
df["test_name"] = df["test_title"].str.split(".py__").str[1].str.split("[").str[0]
df["test_opcode"] = np.where(
    df["test_name"].isin(opcodes_in_test_name_list),
    df["test_name"].str.split("_").str[1].str.upper(),
    df["test_title"].str.split("opcode_").str[1].str.split("-").str[0],
)
df["test_opcode"] = df["test_opcode"].str.split("]").str[0]
df["test_params_str"] = (
    df["test_title"]
    .str.split("[")
    .str[1]
    .str.split("]")
    .str[0]
    .str.split("benchmark_test-")
    .str[1]
)
df["test_params"] = (
    df["test_params_str"]
    .str.split("-")
    .apply(
        lambda x: (
            [item for item in x if item[:6] not in ["opcode", "opcoun", ""]]
            if isinstance(x, list)
            else []
        )
    )
)
df["test_params"] = np.where(
    df["test_params"].str.len() == 0, np.nan, df["test_params"]
)
df["test_params_str"] = df["test_params"].apply(
    lambda x: "-".join(x) if isinstance(x, list) else np.nan
)
# alt_bn precompiles
df["test_opcode"] = np.where(
    (df["test_name"] == "test_alt_bn128") & (df["test_params_str"].str.contains("add")),
    "ECADD",
    df["test_opcode"],
)
df["test_opcode"] = np.where(
    (df["test_name"] == "test_alt_bn128") & (df["test_params_str"].str.contains("mul")),
    "ECMUL",
    df["test_opcode"],
)
# BLS12 precompiles
df["test_opcode"] = np.where(
    df["test_name"] == "test_bls12_381",
    df["test_params_str"].str.split("-").str[0].str.upper(),
    df["test_opcode"],
)
df

,test_title,client_name,run_duration_ms,opcount,ingestion_timestamp,test_file,test_name,test_opcode,test_params_str,test_params
0,test_account_query.py__test_ext_account_query_...,geth,677.96643,800,2026-01-11 18:14:09.323266+00:00,test_account_query,test_ext_account_query_warm,CALLCODE,initial_storage_True-initial_balance_True-empt...,"[initial_storage_True, initial_balance_True, e..."
1,test_memory.py__test_mcopy[fork_Prague-benchma...,geth,270.07925,3000,2026-01-11 18:14:09.323266+00:00,test_memory,test_mcopy,MCOPY,fixed_src_dst_True-copy_size_32-32 bytes,"[fixed_src_dst_True, copy_size_32, 32 bytes]"
2,test_stack.py__test_push[fork_Prague-benchmark...,geth,1566.43530,70000,2026-01-11 18:14:09.323266+00:00,test_stack,test_push,PUSH14,NaN,NaN
3,test_identity.py__test_identity_fixed_size[for...,geth,448.79470,800,2026-01-11 18:14:09.323266+00:00,test_identity,test_identity_fixed_size,IDENTITY,size_0,[size_0]
4,test_log.py__test_log_benchmark[fork_Prague-be...,geth,490.98914,27,2026-01-11 18:14:09.323266+00:00,test_log,test_log_benchmark,LOG0,log_size_1024-mem_size_256,"[log_size_1024, mem_size_256]"
...,...,...,...,...,...,...,...,...,...,...
58523,test_block_context.py__test_blockhash[fork_Pra...,nethermind,260.43994,10000,2026-01-12 10:01:37.327759+00:00,test_block_context,test_blockhash,BLOCKHASH,genesis,[genesis]
58524,test_control_flow.py__test_gas_op[fork_Prague-...,nethermind,117.03787,12000,2026-01-12 10:01:37.327759+00:00,test_control_flow,test_gas_op,GAS,NaN,NaN
58525,test_stack.py__test_push[fork_Prague-benchmark...,nethermind,591.46630,49000,2026-01-12 10:01:37.327759+00:00,test_stack,test_push,PUSH2,NaN,NaN
58526,test_log.py__test_log_benchmark[fork_Prague-be...,nethermind,323.90646,27,2026-01-12 10:01:37.327759+00:00,test_log,test_log_benchmark,LOG2,log_size_1024-mem_size_1024,"[log_size_1024, mem_size_1024]"
58527,test_memory.py__test_mcopy[fork_Prague-benchma...,nethermind,132.56820,1500,2026-01-12 10:01:37.327759+00:00,test_memory,test_mcopy,MCOPY,fixed_src_dst_True-copy_size_1024-1MiB,"[fixed_src_dst_True, copy_size_1024, 1MiB]"

In [8]:
df[df["test_opcode"].isna()]["test_name"].unique()

array([], dtype=object)

## Opcode counts

In [9]:
df["opcount"].value_counts()

opcount
14000     1504
70000     1296
21000     1264
35000     1248
7000      1248
          ...
375         16
280         16
52500       16
128         16
140000      16
Name: count, Length: 177, dtype: int64

In [10]:
0 in df["opcount"].value_counts().index

False

In [11]:
df["opcount"].isna().sum()/len(df)

np.float64(0.0)

Ok, no empty opcode counts now.

## Run times

In [12]:
df['run_duration_ms'].describe()

count    58528.000000
mean       619.194508
std        886.706005
min          0.000000
25%        162.397832
50%        346.372710
75%        731.651045
max      15415.144000
Name: run_duration_ms, dtype: float64

In [13]:
sum(df["run_duration_ms"]==0.0)/len(df)

0.0002733734281027884

Ok, almost no test with zero run time

In [14]:
df[df["run_duration_ms"]==0.0]

,test_title,client_name,run_duration_ms,opcount,ingestion_timestamp,test_file,test_name,test_opcode,test_params_str,test_params
1048,test_sha256.py__test_sha256_fixed_size[fork_Pr...,geth,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
4718,test_sha256.py__test_sha256_fixed_size[fork_Pr...,besu,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
8387,test_sha256.py__test_sha256_fixed_size[fork_Pr...,reth,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
12048,test_sha256.py__test_sha256_fixed_size[fork_Pr...,nethermind,0.0,500,2026-01-11 18:14:09.323266+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
15704,test_sha256.py__test_sha256_fixed_size[fork_Pr...,geth,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
19361,test_sha256.py__test_sha256_fixed_size[fork_Pr...,besu,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
23015,test_sha256.py__test_sha256_fixed_size[fork_Pr...,reth,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
26671,test_sha256.py__test_sha256_fixed_size[fork_Pr...,nethermind,0.0,500,2026-01-11 23:39:48.835843+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
30327,test_sha256.py__test_sha256_fixed_size[fork_Pr...,geth,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
33983,test_sha256.py__test_sha256_fixed_size[fork_Pr...,besu,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
37640,test_sha256.py__test_sha256_fixed_size[fork_Pr...,reth,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
41296,test_sha256.py__test_sha256_fixed_size[fork_Pr...,nethermind,0.0,500,2026-01-12 05:05:43.444247+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
44954,test_sha256.py__test_sha256_fixed_size[fork_Pr...,geth,0.0,500,2026-01-12 10:01:37.327759+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
48611,test_sha256.py__test_sha256_fixed_size[fork_Pr...,besu,0.0,500,2026-01-12 10:01:37.327759+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
52266,test_sha256.py__test_sha256_fixed_size[fork_Pr...,reth,0.0,500,2026-01-12 10:01:37.327759+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]
55920,test_sha256.py__test_sha256_fixed_size[fork_Pr...,nethermind,0.0,500,2026-01-12 10:01:37.327759+00:00,test_sha256,test_sha256_fixed_size,SHA256,size_1024,[size_1024]

These are all from the same test:

In [15]:
df[df["run_duration_ms"]==0.0]["test_title"].unique()

array(['test_sha256.py__test_sha256_fixed_size[fork_Prague-benchmark_test-size_1024-opcount_500.0K]'],
      dtype=object)

## Missing opcodes

In [16]:
non_zero_df = df[df["run_duration_ms"]!=0.0].copy()
benchmarked_operations = set(non_zero_df["test_opcode"].unique().tolist())
all_operations = set(operation_types.ALL_OPERATIONS)

In [17]:
misnamed_operations = benchmarked_operations - all_operations
print(f"Number of misnamed operations: {len(misnamed_operations)}")
misnamed_operations

Number of misnamed operations: 7

{'BLS12_FP_TO_G1',
 'BLS12_FP_TO_G2',
 'JUMPDESTS',
 'KECCAK',
 'POINT',
 'RIPEMD160',
 'SHA256'}

In [18]:
missing_operations = all_operations - benchmarked_operations
print(f"Number of missing operations: {len(missing_operations)-len(misnamed_operations)}")
missing_operations

Number of missing operations: 19

{'ADDMOD',
 'BLOBHASH',
 'BLS12_G1MSM',
 'BLS12_G2MSM',
 'BLS12_MAP_FP2_TO_G2',
 'BLS12_MAP_FP_TO_G1',
 'BLS12_PAIRING_CHECK',
 'DIFFICULTY',
 'ECPAIRING',
 'INVALID',
 'JUMP',
 'JUMPDEST',
 'KECCAK256',
 'MODEXP',
 'MULMOD',
 'P256VERIFY',
 'POINT_EVALUATION',
 'POP',
 'RETURN',
 'REVERT',
 'RIPEMD-160',
 'SELFDESTRUCT',
 'SHA2-256',
 'SLOAD',
 'SSTORE',
 'STOP'}

## Test configurations

In [19]:
test_configs = non_zero_df[non_zero_df["test_params"].notna()].drop_duplicates("test_params_str")[
    ["test_opcode", "test_params"]
].sort_values("test_opcode")

test_configs

     test_opcode                           test_params
187      BLAKE2F                             [blake2f]
357    BLOCKHASH                             [genesis]
220    BLOCKHASH                              [random]
193    BLOCKHASH                       [current_block]
119    BLOCKHASH                             [block_1]
..           ...                                   ...
367  SELFBALANCE                  [contract_balance_1]
60        SHA256                             [size_32]
78        SHA256                            [size_256]
48         TLOAD    [fixed_value_True, fixed_key_True]
386       TSTORE  [fixed_value_False, fixed_key_False]

[168 rows x 2 columns]

In [20]:
non_simple_configs = test_configs[
    ~test_configs["test_opcode"].isin(operation_types.SIMPLE_COMPUTE)
]
temp_ops = non_simple_configs["test_opcode"].unique()
for op in temp_ops:
    print(f"configs for {op}:")
    op_configs = non_simple_configs[non_simple_configs["test_opcode"] == op][
        "test_params"
    ]
    for t in op_configs:
        print(f"  - {t}")

configs for BLAKE2F:
  - ['blake2f']
configs for BLS12_FP_TO_G1:
  - ['bls12_fp_to_g1']
configs for BLS12_FP_TO_G2:
  - ['bls12_fp_to_g2']
configs for BLS12_G1ADD:
  - ['bls12_g1add']
configs for BLS12_G2ADD:
  - ['bls12_g2add']
configs for CALLCODE:
  - ['initial_storage_True', 'initial_balance_True', 'empty_code_True']
configs for CALLDATACOPY:
  - ['calldata_size_32', 'fixed_src_dst_True', '10KiB']
  - ['calldata_size_0', 'fixed_src_dst_True', '1KiB']
  - ['calldata_size_1024', 'fixed_src_dst_True', '0 bytes']
  - ['calldata_size_32', 'fixed_src_dst_True', '256 bytes']
  - ['calldata_size_1024', 'fixed_src_dst_True', '1KiB']
  - ['calldata_size_1024', 'fixed_src_dst_True', '1MiB']
  - ['calldata_size_32', 'fixed_src_dst_True', '0 bytes']
  - ['calldata_size_32', 'fixed_src_dst_True', '1KiB']
  - ['calldata_size_0', 'fixed_src_dst_True', '10KiB']
  - ['calldata_size_256', 'fixed_src_dst_True', '32 bytes']
  - ['calldata_size_256', 'fixed_src_dst_True', '0 bytes']
  - ['calldata_size_32', 'fixed_src_dst_True', '1MiB']
  - ['calldata_size_256', 'fixed_src_dst_True', '256 bytes']
  - ['calldata_size_0', 'fixed_src_dst_True', '32 bytes']
  - ['calldata_size_1024', 'fixed_src_dst_True', '256 bytes']
  - ['calldata_size_0', 'fixed_src_dst_True', '1MiB']
  - ['calldata_size_256', 'fixed_src_dst_True', '1MiB']
  - ['calldata_size_256', 'fixed_src_dst_True', '10KiB']
  - ['calldata_size_1024', 'fixed_src_dst_True', '32 bytes']
  - ['calldata_size_1024', 'fixed_src_dst_True', '10KiB']
  - ['calldata_size_32', 'fixed_src_dst_True', '32 bytes']
  - ['calldata_size_0', 'fixed_src_dst_True', '0 bytes']
  - ['calldata_size_256', 'fixed_src_dst_True', '1KiB']
  - ['calldata_size_0', 'fixed_src_dst_True', '256 bytes']
configs for CODECOPY:
  - ['code_size_32', 'mem_size_0']
  - ['code_size_32', 'mem_size_32']
  - ['code_size_32', 'mem_size_1024']
  - ['code_size_32', 'mem_size_256']
  - ['code_size_0', 'mem_size_1024']
  - ['code_size_256', 'mem_size_32']
  - ['code_size_24576', 'mem_size_32']
  - ['code_size_256', 'mem_size_256']
  - ['code_size_1024', 'mem_size_32']
  - ['code_size_256', 'mem_size_1024']
  - ['code_size_24576', 'mem_size_0']
  - ['code_size_24576', 'mem_size_256']
  - ['code_size_256', 'mem_size_0']
  - ['code_size_0', 'mem_size_32']
  - ['code_size_24576', 'mem_size_1024']
  - ['code_size_1024', 'mem_size_256']
  - ['code_size_1024', 'mem_size_0']
  - ['code_size_1024', 'mem_size_1024']
  - ['code_size_0', 'mem_size_0']
  - ['code_size_0', 'mem_size_256']
configs for CREATE:
  - ['0 bytes without value']
configs for CREATE2:
  - ['0 bytes with value']
configs for ECADD:
  - ['bn128_add']
  - ['bn128_add_infinities']
configs for ECMUL:
  - ['bn128_mul_32_byte_coord_and_2_scalar']
  - ['bn128_mul_infinities_32_byte_scalar']
  - ['bn128_mul_32_byte_coord_and_scalar']
configs for ECRECOVER:
  - ['ecrecover']
configs for EXTCODECOPY:
  - ['512']
configs for IDENTITY:
  - ['size_0']
configs for KECCAK:
  - ['msg_size_256', 'mem_size_32']
  - ['msg_size_0', 'mem_size_0']
  - ['msg_size_1024', 'mem_size_32']
  - ['msg_size_32', 'mem_size_0']
  - ['msg_size_0', 'mem_size_256']
  - ['msg_size_1024', 'mem_size_256']
  - ['msg_size_32', 'mem_size_32']
  - ['msg_size_1024', 'mem_size_1024']
  - ['msg_size_32', 'mem_size_1024']
  - ['msg_size_0', 'mem_size_1024']
  - ['msg_size_0', 'mem_size_32']
  - ['msg_size_256', 'mem_size_0']
  - ['msg_size_256', 'mem_size_1024']
  - ['msg_size_256', 'mem_size_256']
  - ['msg_size_1024', 'mem_size_0']
  - ['msg_size_32', 'mem_size_256']
configs for LOG0:
  - ['log_size_256', 'mem_size_256']
  - ['log_size_32', 'mem_size_256']
  - ['log_size_0', 'mem_size_0']
  - ['log_size_256', 'mem_size_1024']
  - ['log_size_32', 'mem_size_1024']
  - ['log_size_1024', 'mem_size_256']
configs for LOG1:
  - ['log_size_0', 'mem_size_1024']
configs for LOG2:
  - ['log_size_32', 'mem_size_32']
  - ['log_size_1024', 'mem_size_1024']
configs for LOG3:
  - ['log_size_1024', 'mem_size_32']
  - ['log_size_0', 'mem_size_256']
  - ['log_size_256', 'mem_size_32']
configs for LOG4:
  - ['log_size_1024', 'mem_size_0']
  - ['log_size_32', 'mem_size_0']
  - ['log_size_256', 'mem_size_0']
  - ['log_size_0', 'mem_size_32']
configs for MCOPY:
  - ['fixed_src_dst_True', 'copy_size_32', '256 bytes']
  - ['fixed_src_dst_True', 'copy_size_1024', '32 bytes']
  - ['fixed_src_dst_True', 'copy_size_32', '32 bytes']
  - ['fixed_src_dst_True', 'copy_size_256', '1MiB']
  - ['fixed_src_dst_True', 'copy_size_0', '32 bytes']
  - ['fixed_src_dst_True', 'copy_size_1024', '1024 bytes']
  - ['fixed_src_dst_True', 'copy_size_256', '256 bytes']
  - ['fixed_src_dst_True', 'copy_size_0', '10KiB']
  - ['fixed_src_dst_True', 'copy_size_32', '10KiB']
  - ['fixed_src_dst_True', 'copy_size_1024', '10KiB']
  - ['fixed_src_dst_True', 'copy_size_256', '0 bytes']
  - ['fixed_src_dst_True', 'copy_size_0', '1MiB']
  - ['fixed_src_dst_True', 'copy_size_256', '1024 bytes']
  - ['fixed_src_dst_True', 'copy_size_32', '1MiB']
  - ['fixed_src_dst_True', 'copy_size_32', '0 bytes']
  - ['fixed_src_dst_True', 'copy_size_0', '0 bytes']
  - ['fixed_src_dst_True', 'copy_size_256', '32 bytes']
  - ['fixed_src_dst_True', 'copy_size_1024', '1MiB']
  - ['fixed_src_dst_True', 'copy_size_32', '1024 bytes']
  - ['fixed_src_dst_True', 'copy_size_256', '10KiB']
  - ['fixed_src_dst_True', 'copy_size_1024', '0 bytes']
  - ['fixed_src_dst_True', 'copy_size_1024', '256 bytes']
  - ['fixed_src_dst_True', 'copy_size_0', '1024 bytes']
  - ['fixed_src_dst_True', 'copy_size_0', '256 bytes']
configs for MSTORE8:
  - ['mem_size_1024', 'offset_initialized_True', 'offset_0']
  - ['mem_size_256', 'offset_initialized_True', 'offset_0']
  - ['mem_size_32', 'offset_initialized_True', 'offset_0']
  - ['mem_size_10240', 'offset_initialized_True', 'offset_0']
  - ['mem_size_0', 'offset_initialized_True', 'offset_0']
configs for POINT:
  - ['point_evaluation']
configs for RETURNDATACOPY:
  - ['fixed_dst_True', '1MiB', 'mem_size_32']
  - ['fixed_dst_True', '256 bytes', 'mem_size_256']
  - ['fixed_dst_True', '10KiB', 'mem_size_0']
  - ['fixed_dst_True', '0 bytes', 'mem_size_0']
  - ['fixed_dst_True', '32 bytes', 'mem_size_32']
  - ['fixed_dst_True', '1024 bytes', 'mem_size_32']
  - ['fixed_dst_True', '256 bytes', 'mem_size_0']
  - ['fixed_dst_True', '1MiB', 'mem_size_256']
  - ['fixed_dst_True', '0 bytes', 'mem_size_32']
  - ['fixed_dst_True', '1024 bytes', 'mem_size_1024']
  - ['fixed_dst_True', '1024 bytes', 'mem_size_0']
  - ['fixed_dst_True', '32 bytes', 'mem_size_1024']
  - ['fixed_dst_True', '256 bytes', 'mem_size_32']
  - ['fixed_dst_True', '10KiB', 'mem_size_32']
  - ['fixed_dst_True', '10KiB', 'mem_size_256']
  - ['fixed_dst_True', '0 bytes', 'mem_size_256']
  - ['fixed_dst_True', '10KiB', 'mem_size_1024']
  - ['fixed_dst_True', '256 bytes', 'mem_size_1024']
  - ['fixed_dst_True', '32 bytes', 'mem_size_0']
  - ['fixed_dst_True', '32 bytes', 'mem_size_256']
  - ['fixed_dst_True', '1MiB', 'mem_size_1024']
  - ['fixed_dst_True', '0 bytes', 'mem_size_1024']
  - ['fixed_dst_True', '1024 bytes', 'mem_size_256']
  - ['fixed_dst_True', '1MiB', 'mem_size_0']
configs for RIPEMD160:
  - ['size_1024']
configs for SHA256:
  - ['size_32']
  - ['size_256']
configs for TLOAD:
  - ['fixed_value_True', 'fixed_key_True']
configs for TSTORE:
  - ['fixed_value_False', 'fixed_key_False']

In [21]:
non_simple_operations = set(operation_types.ALL_OPERATIONS).difference(operation_types.SIMPLE_COMPUTE)
configed_operations = set(test_configs["test_opcode"].unique())
configed_operations

print(f"Operations without configs: {len(non_simple_operations)-len(misnamed_operations)}")
non_simple_operations.difference(configed_operations)

Operations without configs: 42

{'BALANCE',
 'BLS12_G1MSM',
 'BLS12_G2MSM',
 'BLS12_MAP_FP2_TO_G2',
 'BLS12_MAP_FP_TO_G1',
 'BLS12_PAIRING_CHECK',
 'CALL',
 'DELEGATECALL',
 'ECPAIRING',
 'EXP',
 'EXTCODEHASH',
 'EXTCODESIZE',
 'KECCAK256',
 'MLOAD',
 'MODEXP',
 'MSTORE',
 'P256VERIFY',
 'POINT_EVALUATION',
 'RETURN',
 'REVERT',
 'RIPEMD-160',
 'SELFDESTRUCT',
 'SHA2-256',
 'SLOAD',
 'SSTORE',
 'STATICCALL'}

## Estimation issues with simple opcodes

In [22]:
results_df = pd.read_csv(os.path.join(report_dir, "simple_opcodes_results.csv"))
results_df

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
0,ADD,geth,28.803542,9.183886e-02,0.024077,2.407107e-21,0.022458,0.025695,0.974046,0.973008,simple_opcode
1,ADD,reth,28.744386,5.152101e-02,0.026196,6.655718e-24,0.024811,0.027581,0.983793,0.983145,simple_opcode
2,ADD,nethermind,28.042257,2.339509e-09,0.018400,2.115981e-36,0.018094,0.018705,0.998378,0.998313,simple_opcode
3,ADD,besu,23.202074,5.716854e-01,0.196366,3.240647e-34,0.192377,0.200355,0.997574,0.997477,simple_opcode
4,ADDRESS,geth,47.426601,3.061375e-01,0.029520,2.499318e-26,0.028018,0.031022,0.983018,0.982411,simple_opcode
...,...,...,...,...,...,...,...,...,...,...,...
439,TIMESTAMP,besu,21.304192,1.357379e-01,0.028781,2.240945e-40,0.028324,0.029239,0.998314,0.998254,simple_opcode
440,XOR,geth,28.597813,4.222760e-02,0.023809,8.640066e-26,0.022542,0.025076,0.981446,0.980783,simple_opcode
441,XOR,reth,34.381666,1.464465e-10,0.008622,9.967185e-30,0.008292,0.008953,0.990288,0.989941,simple_opcode
442,XOR,nethermind,32.291447,1.186489e-05,0.029107,8.855490e-38,0.028534,0.029681,0.997416,0.997324,simple_opcode
443,XOR,besu,28.245813,1.459965e-03,0.074085,8.681120e-46,0.073330,0.074840,0.999308,0.999283,simple_opcode

In [23]:
simple_compute_opcodes = set(operation_types.SIMPLE_COMPUTE)
estimated_operations = simple_compute_opcodes - missing_operations

estimated_operations_without_errors = set(results_df["opcode"].unique().tolist())
estimated_operations_with_errors = (
    estimated_operations - estimated_operations_without_errors
)

print(
    f"Number of simple operations with estimation errors: {len(estimated_operations_with_errors)}"
)
estimated_operations_with_errors

Number of simple operations with estimation errors: 0

set()

#### Negative slopes

In [24]:
results_df[results_df["slope"]<0]

Empty DataFrame
Columns: [opcode, client, intercept, intercept_pvalue, slope, slope_pvalue, slope_conf_int_low, slope_conf_int_high, rsquared, rsquared_adj, type]
Index: []

#### Non-significant slopes (by p-value)

In [25]:
results_df[results_df["slope_pvalue"]>0.05]

Empty DataFrame
Columns: [opcode, client, intercept, intercept_pvalue, slope, slope_pvalue, slope_conf_int_low, slope_conf_int_high, rsquared, rsquared_adj, type]
Index: []

In [26]:
non_significant_ops = results_df[results_df["slope_pvalue"]>0.05]["opcode"].unique().tolist()
non_significant_ops

[]

#### Small r-squared values (besides non-significant slopes)

In [27]:
results_df[(results_df["rsquared"]<0.5) & (~results_df["opcode"].isin(non_significant_ops))]

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
23,BLOCKHASH,besu,27.777196,0.493704,0.072788,2.346026e-21,0.059894,0.085681,0.456792,0.453122,simple_opcode
28,CALLDATALOAD,geth,35.369647,0.677430,0.029068,6.299082e-19,0.023654,0.034482,0.489282,0.484954,simple_opcode

In [28]:
results_df[(results_df["rsquared"]<0.5) & (~results_df["opcode"].isin(non_significant_ops))]["opcode"].unique()

array(['BLOCKHASH', 'CALLDATALOAD'], dtype=object)