# Gas benchmark data - EDA v2

#### Maria Silva, December 2025

In [17]:
import os
import sys
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

import warnings
warnings.filterwarnings("ignore")

In [2]:
# plotting theme
sns.set_theme(
    style="whitegrid", palette="Set2", rc={"figure.dpi": 500, "axes.titlesize": 15}
)

## Load data from DB

In this analysis, we are using data generated by running the [EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks). The database is hosted on a PostgreSQL server managed by the Nethermind team.

In [46]:
# Main directories
current_path = os.getcwd()
repo_dir = os.path.abspath(os.path.join(current_path, ".."))
report_dir = os.path.join(
    repo_dir, "reports", "opcode_run_times_estimation", "2025-12-19_2025-12-23"
)
src_dir = os.path.join(repo_dir, "src")

# Other files
opcodes_file_name = os.path.abspath(
    os.path.join(repo_dir, "src", "opcodes_in_test_name.txt")
)
with open(opcodes_file_name, "r") as f:
    opcodes_in_test_name_list = [line.strip() for line in f.readlines()]

In [20]:
sys.path.append(src_dir)
import operation_types

In [4]:
# Secrets for acessing xatu clickhouse and erigon
with open(os.path.join(repo_dir, "secrets.json"), "r") as file:
    secrets_dict = json.load(file)

# Credentials for gas bench postgresql
user = secrets_dict["gas_bench_username"]
password = secrets_dict["gas_bench_password"]

In [5]:
gas_bench_db_url = f"postgresql://{user}:{password}@perfnet.core.nethermind.dev:5432/monitoring"
start_date = "2025-12-19"
query_str = f"""
SELECT 
    test_title,
    client_name,
    raw_run_duration_ms AS run_duration_ms,
    opcount,
    ingestion_timestamp
FROM repricings2
WHERE ingestion_timestamp >= '{start_date}'::timestamp
"""
engine = create_engine(gas_bench_db_url)
raw_df = pd.read_sql(query_str, con=engine)
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40862 entries, 0 to 40861
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   test_title           40862 non-null  object
 1   client_name          40862 non-null  object
 2   run_duration_ms      40862 non-null  float64
 3   opcount              40862 non-null  int64
 4   ingestion_timestamp  40862 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(1), int64(1), object(2)
memory usage: 1.6+ MB

Now we can parse the test name info:

In [34]:
df = raw_df.copy()
df["test_file"] = (
    df["test_title"].str.replace("tests_benchmark_", "").str.split(".py").str[0]
)
df["test_name"] = df["test_title"].str.split(".py__").str[1].str.split("[").str[0]
df["test_opcode"] = np.where(
    df["test_name"].isin(opcodes_in_test_name_list),
    df["test_name"].str.split("_").str[1].str.upper(),
    df["test_title"].str.split("opcode_").str[1].str.split("-").str[0],
)
df["test_opcode"] = df["test_opcode"].str.split("]").str[0]
df["test_params_str"] = (
    df["test_title"]
    .str.split("[")
    .str[1]
    .str.split("]")
    .str[0]
    .str.split("benchmark_test-")
    .str[1]
)
df["test_params"] = (
    df["test_params_str"]
    .str.split("-")
    .apply(
        lambda x: (
            [item for item in x if item[:6] not in ["opcode", ""]]
            if isinstance(x, list)
            else []
        )
    )
)
df["test_params"] = np.where(
    df["test_params"].str.len() == 0, np.nan, df["test_params"]
)
df

,test_title,client_name,run_duration_ms,opcount,ingestion_timestamp,test_file,test_name,test_opcode,test_params_str,test_params
0,test_system.py__test_create[fork_Prague-opcoun...,nethermind,0.0,4000,2025-12-19 01:30:53.971702+00:00,test_system,test_create,CREATE2,0 bytes without value-opcode_CREATE2,[0 bytes without value]
1,test_stack.py__test_push[fork_Prague-opcount_1...,nethermind,0.0,100000000,2025-12-19 01:30:53.971702+00:00,test_stack,test_push,PUSH29,opcode_PUSH29,NaN
2,test_stack.py__test_push[fork_Prague-opcount_5...,nethermind,0.0,50000000,2025-12-19 01:30:53.971702+00:00,test_stack,test_push,PUSH23,opcode_PUSH23,NaN
3,test_call_context.py__test_returndatasize_zero...,nethermind,0.0,150000000,2025-12-19 01:30:53.971702+00:00,test_call_context,test_returndatasize_zero,RETURNDATASIZE,NaN,NaN
4,test_bitwise.py__test_bitwise[fork_Prague-opco...,nethermind,0.0,15000000,2025-12-19 01:30:53.971702+00:00,test_bitwise,test_bitwise,OR,opcode_OR-,NaN
...,...,...,...,...,...,...,...,...,...,...
40857,test_block_context.py__test_block_context_ops[...,erigon,0.0,250000000,2025-12-22 05:57:02.203746+00:00,test_block_context,test_block_context_ops,COINBASE,opcode_COINBASE,NaN
40858,test_stack.py__test_push[fork_Prague-opcount_1...,erigon,0.0,12500000,2025-12-22 05:57:02.203746+00:00,test_stack,test_push,PUSH16,opcode_PUSH16,NaN
40859,test_stack.py__test_push[fork_Prague-opcount_1...,erigon,0.0,125000000,2025-12-22 05:57:02.203746+00:00,test_stack,test_push,PUSH14,opcode_PUSH14,NaN
40860,test_account_query.py__test_ext_account_query_...,erigon,0.0,800000,2025-12-22 05:57:02.203746+00:00,test_account_query,test_ext_account_query_warm,STATICCALL,initial_storage_True-initial_balance_True-empt...,"[initial_storage_True, initial_balance_True, e..."
40861,test_stack.py__test_push[fork_Prague-opcount_6...,erigon,0.0,62500000,2025-12-22 05:57:02.203746+00:00,test_stack,test_push,PUSH23,opcode_PUSH23,NaN

## Opcode counts

In [7]:
df["opcount"].value_counts()

opcount
50000000     3235
25000000     3184
75000000     3003
100000000    2813
37500000     2431
             ...
64000          25
500000000      25
125000          9
188000          9
63000           9
Name: count, Length: 114, dtype: int64

In [8]:
df["opcount"].isna().sum()/len(df)

np.float64(0.0)

Ok, no empty opcode counts now.

## Run times

In [9]:
df['run_duration_ms'].describe()

count    40862.000000
mean      1199.225798
std       2331.088122
min          0.000000
25%          0.000000
50%        443.528570
75%       1254.821625
max      29988.809000
Name: run_duration_ms, dtype: float64

In [10]:
sum(df["run_duration_ms"]==0.0)/len(df)

0.252973422739954

Ok, we still have 25% of tests with zero run times... Let's investigate this

In [11]:
df[df["run_duration_ms"]==0.0]["ingestion_timestamp"].unique()

<DatetimeArray>
['2025-12-19 01:30:53.971702+00:00', '2025-12-19 02:35:17.292695+00:00',
 '2025-12-19 02:07:17.433041+00:00', '2025-12-19 02:37:33.047222+00:00',
 '2025-12-19 06:52:57.022048+00:00', '2025-12-20 05:11:20.176072+00:00',
 '2025-12-20 17:10:44.757804+00:00', '2025-12-21 05:04:52.760670+00:00',
 '2025-12-21 17:00:41.743806+00:00', '2025-12-22 05:57:02.203746+00:00']
Length: 10, dtype: datetime64[ns, UTC]

In [12]:
df[df["run_duration_ms"]==0.0]["client_name"].unique()

array(['nethermind', 'besu', 'erigon'], dtype=object)

In [13]:
df[df["run_duration_ms"]==0.0]["test_opcode"].unique()

array(['CREATE2', 'PUSH29', 'PUSH23', 'RETURNDATASIZE', 'OR', 'DUP16',
       'SWAP12', 'MSIZE', 'PUSH3', 'PUSH18', 'MOD', 'SWAP7', 'MSTORE',
       'LT', 'DUP4', 'SDIV', 'EXTCODEHASH', 'PUSH26', 'ADD', 'TSTORE',
       'CALLDATALOAD', 'BLOBBASEFEE', 'CREATE', 'TLOAD', 'SWAP2', 'DUP10',
       'MLOAD', 'PUSH2', 'SELFDESTRUCT', 'SWAP14', 'SWAP16', 'SWAP1',
       'PUSH27', 'PUSH22', 'SHR', 'KECCAK', 'EXTCODECOPY', 'PUSH0', 'GAS',
       'BLOCKHASH', 'PC', 'PREVRANDAO', 'PUSH1', 'DUP2', 'NUMBER', 'DUP3',
       'ORIGIN', 'SAR', 'SGT', 'SMOD', 'DUP6', 'TIMESTAMP', 'PUSH4',
       'SWAP5', 'DUP14', 'CALLDATASIZE', 'PUSH28', 'MSTORE8', 'SWAP15',
       'CALLVALUE', 'CALLCODE', 'GT', 'CALLDATACOPY', 'EXTCODESIZE',
       'JUMPDESTS', 'EXP', 'SWAP11', 'PUSH21', 'DUP12', 'CODECOPY',
       'RETURNDATACOPY', 'BASEFEE', 'SLT', 'SWAP8', 'PUSH24', 'PUSH12',
       'AND', 'MCOPY', 'PUSH31', 'DUP11', 'MUL', 'BYTE', 'PUSH7',
       'PUSH15', 'DUP1', 'DIV', 'PUSH20', 'PUSH32', 'PUSH6', 'PUSH10',
       'PUSH14', 'PUSH9', 'BALANCE', 'GASPRICE', 'XOR', 'SWAP3',
       'COINBASE', 'PUSH25', 'PUSH11', 'PUSH17', 'SWAP10', 'ADDRESS',
       'PUSH19', 'PUSH5', 'DUP8', 'DUP13', 'CHAINID', 'DUP9',
       'DELEGATECALL', 'SWAP6', 'JUMPI', 'PUSH16', 'CODESIZE', 'DUP7',
       'PUSH8', 'SIGNEXTEND', 'SWAP13', 'PUSH30', 'SHL', 'PUSH13',
       'STATICCALL', 'ISZERO', 'CALLER', 'SWAP4', 'SUB', 'CALL',
       'GASLIMIT', 'DUP15', 'DUP5', 'EQ', 'SWAP9', 'NOT', 'SELFBALANCE'],
      dtype=object)

Multiple clients, runs and opcodes seem to be affected. We should also note that these zeros are not consistent, i.e., all opcodes with zero run times also have other runs with non-zero run times:

In [14]:
zero_list = df[df["run_duration_ms"]==0.0]["test_opcode"].unique().tolist()
print(len(zero_list))
t = df[(df["test_opcode"].isin(zero_list)) & (df["run_duration_ms"]!=0.0)]["test_opcode"].unique()
print(len(t))
t

133
133

array(['SELFBALANCE', 'CREATE2', 'PUSH29', 'PUSH23', 'RETURNDATASIZE',
       'OR', 'DUP16', 'SWAP12', 'MSIZE', 'PUSH3', 'PUSH18', 'MOD',
       'SWAP7', 'MSTORE', 'LT', 'DUP4', 'SDIV', 'EXTCODEHASH', 'PUSH26',
       'ADD', 'TSTORE', 'CALLDATALOAD', 'BLOBBASEFEE', 'CREATE', 'TLOAD',
       'SWAP2', 'DUP10', 'MLOAD', 'PUSH2', 'SELFDESTRUCT', 'SWAP14',
       'SWAP16', 'SWAP1', 'PUSH27', 'PUSH22', 'SHR', 'KECCAK',
       'EXTCODECOPY', 'PUSH0', 'GAS', 'BLOCKHASH', 'PC', 'PREVRANDAO',
       'PUSH1', 'DUP2', 'NUMBER', 'DUP3', 'ORIGIN', 'SAR', 'SGT', 'SMOD',
       'DUP6', 'TIMESTAMP', 'PUSH4', 'SWAP5', 'DUP14', 'CALLDATASIZE',
       'PUSH28', 'MSTORE8', 'SWAP15', 'CALLVALUE', 'CALLCODE', 'GT',
       'CALLDATACOPY', 'EXTCODESIZE', 'JUMPDESTS', 'EXP', 'SWAP11',
       'PUSH21', 'DUP12', 'CODECOPY', 'RETURNDATACOPY', 'BASEFEE', 'SLT',
       'SWAP8', 'PUSH24', 'PUSH12', 'AND', 'MCOPY', 'PUSH31', 'DUP11',
       'MUL', 'BYTE', 'PUSH7', 'PUSH15', 'DUP1', 'DIV', 'PUSH20',
       'PUSH32', 'PUSH6', 'PUSH10', 'PUSH14', 'PUSH9', 'BALANCE',
       'GASPRICE', 'XOR', 'SWAP3', 'COINBASE', 'PUSH25', 'PUSH11',
       'PUSH17', 'SWAP10', 'ADDRESS', 'PUSH19', 'PUSH5', 'DUP8', 'DUP13',
       'CHAINID', 'DUP9', 'DELEGATECALL', 'SWAP6', 'JUMPI', 'PUSH16',
       'CODESIZE', 'DUP7', 'PUSH8', 'SIGNEXTEND', 'SWAP13', 'PUSH30',
       'SHL', 'PUSH13', 'STATICCALL', 'ISZERO', 'CALLER', 'SWAP4', 'SUB',
       'CALL', 'GASLIMIT', 'DUP15', 'DUP5', 'EQ', 'SWAP9', 'NOT'],
      dtype=object)

This may be again issues with the run time of the tests. So we can probably drop these zeros for now.

## Missing opcodes

In [35]:
non_zero_df = df[df["run_duration_ms"]!=0.0].copy()
benchmarked_operations = set(non_zero_df["test_opcode"].unique().tolist())
all_operations = set(operation_types.ALL_OPERATIONS)

In [26]:
misnamed_operations = benchmarked_operations - all_operations
print(f"Number of misnamed operations: {len(misnamed_operations)}")
misnamed_operations

Number of misnamed operations: 2

{'JUMPDESTS', 'KECCAK'}

In [28]:
missing_operations = all_operations - benchmarked_operations
print(f"Number of missing operations: {len(missing_operations)-len(misnamed_operations)}")
missing_operations

Number of missing operations: 35

{'ADDMOD',
 'BLAKE2F',
 'BLOBHASH',
 'BLS12_G1ADD',
 'BLS12_G1MSM',
 'BLS12_G2ADD',
 'BLS12_G2MSM',
 'BLS12_MAP_FP2_TO_G2',
 'BLS12_MAP_FP_TO_G1',
 'BLS12_PAIRING_CHECK',
 'DIFFICULTY',
 'ECADD',
 'ECMUL',
 'ECPAIRING',
 'ECRECOVER',
 'IDENTITY',
 'INVALID',
 'JUMP',
 'JUMPDEST',
 'KECCAK256',
 'LOG0',
 'LOG1',
 'LOG2',
 'LOG3',
 'LOG4',
 'MODEXP',
 'MULMOD',
 'P256VERIFY',
 'POINT_EVALUATION',
 'POP',
 'RETURN',
 'REVERT',
 'RIPEMD-160',
 'SHA2-256',
 'SLOAD',
 'SSTORE',
 'STOP'}

## Test configurations

In [37]:
non_zero_df[non_zero_df["test_params"].notna()].drop_duplicates("test_params_str")[
    ["test_opcode", "test_params"]
].sort_values("test_opcode")

         test_opcode                                        test_params
2415         BALANCE  [initial_storage_True, initial_balance_True, e...
2620       BLOCKHASH                                    [current_block]
2494       BLOCKHASH                                           [random]
2384       BLOCKHASH                                          [genesis]
2335       BLOCKHASH                                          [block_1]
2318       BLOCKHASH                                        [block_256]
2609            CALL  [initial_storage_True, initial_balance_True, e...
2350        CALLCODE  [initial_storage_True, initial_balance_True, e...
2353    CALLDATACOPY  [non_zero_data_False, fixed_src_dst_True, 0 by...
2293    CALLDATALOAD                                       [zero, loop]
2338    CALLDATASIZE                            [calldata_length_10000]
2349       CALLVALUE                              [non_zero_value_True]
2367        CODECOPY                      [fixed_src_dst_True, 0 bytes]
2295          CREATE                            [0 bytes without value]
2404          CREATE                               [0 bytes with value]
2302         CREATE2                               [0 bytes with value]
2272         CREATE2                            [0 bytes without value]
2482    DELEGATECALL  [initial_storage_True, initial_balance_True, e...
2397             DIV                                                [0]
2312     EXTCODECOPY                                              [512]
2289     EXTCODEHASH  [initial_storage_True, initial_balance_True, e...
2354     EXTCODESIZE  [initial_storage_True, initial_balance_True, e...
2300           MLOAD  [big_memory_expansion_True, offset_initialized...
2370             MOD                                     [mod_bits_127]
2279           MSIZE                                       [mem_size_1]
2285          MSTORE  [big_memory_expansion_True, offset_initialized...
2346         MSTORE8  [big_memory_expansion_True, offset_initialized...
2368  RETURNDATACOPY                          [fixed_dst_True, 0 bytes]
2298  RETURNDATASIZE  [returned_size_0, return_data_style_ReturnData...
2288            SDIV                                                [0]
108      SELFBALANCE                               [contract_balance_1]
2330            SMOD                                     [mod_bits_127]
2568      STATICCALL  [initial_storage_True, initial_balance_True, e...
2296           TLOAD                 [fixed_value_True, fixed_key_True]
2292          TSTORE               [fixed_value_False, fixed_key_False]

## Estimation issues with simple opcodes

In [47]:
results_df = pd.read_csv(os.path.join(report_dir, "simple_opcodes_results.csv"))
results_df

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
0,ADD,nethermind,36.477645,5.046740e-11,2.647634e-05,5.258084e-103,2.623207e-05,2.672061e-05,0.998460,0.998439,simple_opcode
1,ADD,reth,47.828787,3.055318e-03,1.569679e-05,5.368605e-50,1.489004e-05,1.650355e-05,0.954326,0.953691,simple_opcode
2,ADD,besu,-82.287973,6.083092e-01,2.017402e-04,8.051566e-57,1.934731e-04,2.100072e-04,0.970473,0.970063,simple_opcode
3,ADD,geth,35.853411,1.797848e-01,2.201855e-05,2.264869e-44,2.064979e-05,2.338731e-05,0.934566,0.933657,simple_opcode
4,ADDRESS,nethermind,2433.534222,9.311506e-72,1.758327e-09,3.807818e-01,-2.216364e-09,5.733018e-09,0.010686,-0.003055,simple_opcode
...,...,...,...,...,...,...,...,...,...,...,...
437,TIMESTAMP,geth,23.762875,4.279698e-03,1.193815e-05,9.287714e-105,1.183402e-05,1.204228e-05,0.998624,0.998604,simple_opcode
438,XOR,nethermind,33.176386,6.766726e-01,1.127608e-05,6.428926e-09,7.861507e-06,1.469066e-05,0.375743,0.367073,simple_opcode
439,XOR,reth,41.815452,1.474103e-19,6.484339e-06,2.159042e-75,6.339127e-06,6.629551e-06,0.990995,0.990870,simple_opcode
440,XOR,besu,-26.960011,8.002678e-01,8.994370e-05,2.854723e-48,8.557848e-05,9.430893e-05,0.963033,0.962465,simple_opcode
441,XOR,geth,52.873507,1.486851e-01,2.186789e-05,2.279828e-40,2.030705e-05,2.342873e-05,0.915496,0.914323,simple_opcode

In [48]:
simple_compute_opcodes = set(operation_types.SIMPLE_COMPUTE)
estimated_operations = simple_compute_opcodes - missing_operations

estimated_operations_without_errors = set(results_df["opcode"].unique().tolist())
estimated_operations_with_errors = (
    estimated_operations - estimated_operations_without_errors
)

print(
    f"Number of simple operations with estimation errors: {len(estimated_operations_with_errors)}"
)
estimated_operations_with_errors

Number of simple operations with estimation errors: 0

set()

#### Negative slopes

In [ ]:
results_df[results_df["slope"]<0]

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
5,ADDRESS,reth,2446.632786,3.665054e-44,-4.413958e-09,0.378728,-1.434856e-08,5.520641e-09,0.010778,-0.002961,simple_opcode
6,ADDRESS,besu,15263.710736,6.505656e-14,-4.465982e-09,0.965658,-2.109819e-07,2.020499e-07,0.000030,-0.016098,simple_opcode
37,CALLER,reth,2404.241729,6.106285e-55,-4.612416e-09,0.180465,-1.141097e-08,2.186142e-09,0.024775,0.011230,simple_opcode
138,GASPRICE,geth,7742.367932,7.311583e-66,-9.777434e-09,0.207051,-2.508636e-08,5.531491e-09,0.022018,0.008435,simple_opcode
184,ORIGIN,reth,2376.562418,1.253489e-77,-2.167508e-09,0.182706,-5.378991e-09,1.043976e-09,0.024525,0.010977,simple_opcode

#### Non-significant slopes (by p-value)

In [50]:
results_df[results_df["slope_pvalue"]>0.05]

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
4,ADDRESS,nethermind,2433.534222,9.311506e-72,1.758327e-09,0.380782,-2.216364e-09,5.733018e-09,0.010686,-0.003055,simple_opcode
5,ADDRESS,reth,2446.632786,3.665054e-44,-4.413958e-09,0.378728,-1.434856e-08,5.520641e-09,0.010778,-0.002961,simple_opcode
6,ADDRESS,besu,15263.710736,6.505656e-14,-4.465982e-09,0.965658,-2.109819e-07,2.020499e-07,0.000030,-0.016098,simple_opcode
7,ADDRESS,geth,11170.630708,3.877395e-89,7.892990e-09,0.135623,-2.532651e-09,1.831863e-08,0.030664,0.017201,simple_opcode
36,CALLER,nethermind,2430.631663,1.979562e-75,6.158509e-10,0.728711,-2.910002e-09,4.141704e-09,0.001681,-0.012185,simple_opcode
37,CALLER,reth,2404.241729,6.106285e-55,-4.612416e-09,0.180465,-1.141097e-08,2.186142e-09,0.024775,0.011230,simple_opcode
38,CALLER,besu,15513.425185,1.069936e-12,3.551054e-08,0.755021,-1.908190e-07,2.618401e-07,0.001508,-0.013853,simple_opcode
39,CALLER,geth,11149.562922,1.759515e-119,7.181267e-10,0.717208,-3.218852e-09,4.655105e-09,0.001833,-0.012030,simple_opcode
136,GASPRICE,nethermind,2220.030581,1.438825e-72,1.500628e-09,0.399843,-2.031500e-09,5.032757e-09,0.009864,-0.003888,simple_opcode
137,GASPRICE,reth,2368.818609,1.000215e-89,1.787958e-09,0.104764,-3.815156e-10,3.957431e-09,0.036133,0.022746,simple_opcode
138,GASPRICE,geth,7742.367932,7.311583e-66,-9.777434e-09,0.207051,-2.508636e-08,5.531491e-09,0.022018,0.008435,simple_opcode
159,MOD,nethermind,8662.699011,1.879822e-08,1.374200e-05,0.716390,-6.087195e-05,8.835596e-05,0.000907,-0.005936,simple_opcode
160,MOD,reth,3417.569320,1.273582e-08,7.379137e-06,0.616425,-2.167218e-05,3.643045e-05,0.001723,-0.005114,simple_opcode
162,MOD,geth,5700.009428,7.522032e-09,1.380481e-05,0.567555,-3.381321e-05,6.142284e-05,0.002243,-0.004591,simple_opcode
183,ORIGIN,nethermind,2157.905766,4.392648e-65,2.274250e-09,0.303687,-2.102010e-09,6.650510e-09,0.014687,0.001002,simple_opcode
184,ORIGIN,reth,2376.562418,1.253489e-77,-2.167508e-09,0.182706,-5.378991e-09,1.043976e-09,0.024525,0.010977,simple_opcode
185,ORIGIN,geth,8313.898887,3.599471e-101,2.679877e-09,0.314640,-2.595864e-09,7.955618e-09,0.014041,0.000347,simple_opcode
362,SMOD,nethermind,9246.927635,4.947078e-08,5.489737e-06,0.895422,-7.690657e-05,8.788605e-05,0.000119,-0.006730,simple_opcode
363,SMOD,reth,3365.165649,1.899611e-08,6.206967e-06,0.672866,-2.278841e-05,3.520234e-05,0.001224,-0.005616,simple_opcode
365,SMOD,geth,5948.306842,1.047569e-08,1.403023e-05,0.581816,-3.620588e-05,6.426634e-05,0.002082,-0.004753,simple_opcode

In [53]:
non_significant_ops = results_df[results_df["slope_pvalue"]>0.05]["opcode"].unique().tolist()
non_significant_ops

['ADDRESS', 'CALLER', 'GASPRICE', 'MOD', 'ORIGIN', 'SMOD']

#### Small r-squared values (besides non-significant slopes)

In [54]:
results_df[(results_df["rsquared"]<0.5) & (~results_df["opcode"].isin(non_significant_ops))]

,opcode,client,intercept,intercept_pvalue,slope,slope_pvalue,slope_conf_int_low,slope_conf_int_high,rsquared,rsquared_adj,type
8,AND,nethermind,33.166363,0.648826,0.000011,7.948117e-10,0.000008,0.000014,0.410285,0.402095,simple_opcode
22,BLOCKHASH,besu,27.317989,0.730944,0.000089,3.732464e-49,0.000079,0.000099,0.446182,0.444678,simple_opcode
179,OR,nethermind,44.593101,0.531045,0.000011,8.342115e-10,0.000008,0.000014,0.409507,0.401306,simple_opcode
438,XOR,nethermind,33.176386,0.676673,0.000011,6.428926e-09,0.000008,0.000015,0.375743,0.367073,simple_opcode